added cloud build

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,5 +1,6 @@
 options:
   logging: CLOUD_LOGGING_ONLY
+  dynamicSubstitutions: true  
 
 steps:
   - name: "python"
@@ -61,3 +62,64 @@ steps:
           echo "Pytest succeeded."
         fi
     waitFor: ["pytest"]   
+
+  - name: "gcr.io/cloud-builders/docker"  
+    id: "build"
+    args: ['build', '-t', '${_IMAGE_PATH}', '.' ]
+
+  - name: "gcr.io/cloud-builders/docker"
+    id: "push"
+    args: ['push', '${_IMAGE_PATH}']
+    waitFor: ["build"]  
+
+  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
+  #   id: "deploy_feature"
+  #   entrypoint: bash
+  #   args:
+  #     - -c
+  #     - |
+  #       if [[ "$BRANCH_NAME" =~ ^feature-.*$ ]]
+  #       then
+  #         gcloud run deploy "${BRANCH_NAME}" --image  "${_IMAGE_PATH}" --region "${_DEPLOY_REGION}" --allow-unauthenticated
+  #       fi
+
+  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
+  #   id: "test_feature"
+  #   entrypoint: bash
+  #   args:
+  #     - -c
+  #     - | 
+  #       if [[ "$BRANCH_NAME" =~ ^feature-.*$ ]]
+  #       then
+  #         gcloud run services describe "${BRANCH_NAME}" --region "${_DEPLOY_REGION}" --format='value(status.url)' | xargs -I {} curl -s "{}" | grep "Employee Data" && echo "Test passed" || (echo "Test failed" && exit 1)
+  #       fi
+
+  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
+  #   id: "register_pipeline"
+    
+  #   entrypoint: bash
+  #   args:
+  #     - -c
+  #     - | 
+  #       if [[ "$BRANCH_NAME" == "main" ]]
+  #       then
+  #         gcloud deploy apply --file=./deploy/clouddeploy.yaml --region=$_DEPLOY_REGION --project=$PROJECT_ID
+  #       fi  
+
+  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
+  #   id: 'create_release'
+  #   entrypoint: 'bash'
+  #   args:
+  #     - '-c'
+  #     - |
+  #       if [[ "$BRANCH_NAME" == "main" ]]
+  #       then
+  #         gcloud deploy releases create emp-portal-$SHORT_SHA --delivery-pipeline emp-portal-pipeline --region $_DEPLOY_REGION --images app-image="$_IMAGE_PATH"
+  #       fi
+
+substitutions:
+  _LOCATION: us-central1-docker.pkg.dev
+  _IMAGE: employee-portal/emp-portal-image
+  _IMAGE_PATH: ${_LOCATION}/${PROJECT_ID}/${_IMAGE}:${BRANCH_NAME}  
+  # _DEPLOY_REGION: us-central1
+
